/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller

object App {
  def main(args: Array[String]): Unit = {
    val conjuntoDifuso = new ConjuntosDifusos()

    val rango = 0 to 10

    // Definimos los conjuntos difusos
    val b = conjuntoDifuso.grande(1, 25)
    val c = conjuntoDifuso.complemento(b)
    println(s"Pertenencia de 10 en b: ${conjuntoDifuso.pertenece(10, b)}")
    println(s"Pertenencia de 10 en c: ${conjuntoDifuso.pertenece(10, c)}")
    
    // Realizamos la intersección y la unión
    val d = conjuntoDifuso.interseccion(b, c)
    val e = conjuntoDifuso.union(b, c)

    // Imprimimos los resultados
    println("\nIntersección (b ∩ c):")
    println(conjuntoDifuso.imprimirConjunto(d, rango))

    println("\nUnión (b U c):")
    println(conjuntoDifuso.imprimirConjunto(e, rango))

    val f = conjuntoDifuso.grande(1,15) 
    println(conjuntoDifuso.imprimirConjunto(conjuntoDifuso.interseccion(b,f), 1 to 35))

    // Verificamos la igualdad entre b y f
    val sonIguales = conjuntoDifuso.igualdad(b, f)
    println(s"\n¿Son iguales b y f? $sonIguales")
  }
}
